stages:
  - build
  - docker_build
  - deploy

variables:
  DOCKER_IMAGE: allower99/project2-nginx-frontend:latest
  SSH_USER: user1
  SSH_HOST: 84.201.168.118
  SSH_PATH: /home/user1/my-nextjs-nginx3

build_app:
  stage: build
  tags:
    - myserver-runner
  script:
    - rm -rf build nextjs-app/.next
    - cd nextjs-app
    - npm ci
    - npm run build
    - cp -r .next ../build/_next        # копируем билд из .next в корень build/_next
    - cp -r public ../build/public     # копируем public тоже в build
  artifacts:
    paths:
      - build

docker_build:
  stage: docker_build
  tags:
    - myserver-runner
  dependencies:
    - build_app
  script:
    - ls -la build        # Проверяем что build есть и с файлами
    - docker build -t $DOCKER_IMAGE .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE


deploy:
  stage: deploy
  tags:
    - myserver-runner
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        echo '🚀 Начинаем деплой...';
        cd $SSH_PATH &&
        docker-compose down &&
        docker-compose pull &&
        docker-compose up -d --force-recreate
      "
  when: manual
